# Generated by Django 3.2.5 on 2023-01-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('timezone', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('circuit', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('tab', models.CharField(max_length=200)),
            ],
        ),
    ]
