# Generated by Django 3.2.5 on 2023-01-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatecalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='tab',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
