# Generated by Django 3.2.5 on 2023-01-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatecalendar', '0002_alter_calendar_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='online',
            field=models.BooleanField(null=True),
        ),
    ]
