# Generated by Django 3.2.5 on 2023-01-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatecalendar', '0003_calendar_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='type',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendar',
            name='circuit',
            field=models.CharField(choices=[('IoNA', 'IoNA'), ('Netherlands', 'Netherlands'), ('Bulkans', 'Bulkans')], max_length=50),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='region',
            field=models.CharField(choices=[('Asia', 'Asia'), ('europe', 'europe'), ('North America', 'North America'), ('Latin America', 'Latin America'), ('Australasia', 'Australasia')], max_length=50),
        ),
    ]
