# Generated by Django 3.2.5 on 2023-01-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatecalendar', '0004_auto_20230126_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='type',
            field=models.CharField(choices=[('Open', 'Open'), ('IV', 'IV'), ('Schools', 'Schools'), ('Juniors', 'Juniors'), ('Pro-am', 'Pro-am'), ('Noives', 'Noives'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
