# Generated by Django 3.2.5 on 2023-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debatecalendar', '0005_alter_calendar_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='circuit',
            field=models.CharField(choices=[('IoNA', 'IoNA'), ('Netherlands', 'Netherlands'), ('Bulkans', 'Bulkans')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='region',
            field=models.CharField(choices=[('Asia', 'Asia'), ('europe', 'europe'), ('North America', 'North America'), ('Latin America', 'Latin America'), ('Australasia', 'Australasia')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='startdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='timezone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='type',
            field=models.CharField(choices=[('Open', 'Open'), ('IV', 'IV'), ('Schools', 'Schools'), ('Juniors', 'Juniors'), ('Pro-am', 'Pro-am'), ('Noives', 'Noives'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
    ]
