# Generated by Django 3.2.5 on 2023-02-01 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='speaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('tournament', models.CharField(max_length=200, null=True)),
                ('round', models.IntegerField(null=True)),
                ('partner', models.CharField(max_length=200, null=True)),
                ('room_points', models.IntegerField(null=True)),
                ('team_position', models.CharField(choices=[('OG', 'OG'), ('OO', 'OO'), ('CG', 'CG'), ('CO', 'CO')], max_length=2, null=True)),
                ('speaker_position', models.CharField(choices=[('PM', 'PM'), ('DPM', 'DPM'), ('LO', 'LO'), ('DLO', 'DLO'), ('MG', 'MG'), ('GW', 'GW'), ('MO', 'MO'), ('OW', 'OW')], max_length=3, null=True)),
                ('motion_type', models.CharField(max_length=50, null=True)),
                ('team_result', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)])),
                ('speaks', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)])),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
