# Generated by Django 3.2.5 on 2023-02-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speakstracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaks',
            old_name='speaks',
            new_name='speaker_score',
        ),
    ]
