# Generated by Django 3.2.5 on 2023-02-02 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speakstracker', '0002_rename_speaks_speaks_speaker_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaks', to=settings.AUTH_USER_MODEL),
        ),
    ]
