# Generated by Django 3.2.5 on 2023-02-03 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakstracker', '0004_alter_speaks_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaks',
            name='team_result',
        ),
        migrations.AddField(
            model_name='speaks',
            name='team_points',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='room_points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='round',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='speaker_score',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
