# Generated by Django 3.2.5 on 2023-03-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakstracker', '0005_auto_20230203_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaks',
            name='info_slide',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='speaks',
            name='motion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='motion_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='partner',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='room_points',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='round',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='speaker_position',
            field=models.CharField(blank=True, choices=[('PM', 'PM'), ('DPM', 'DPM'), ('LO', 'LO'), ('DLO', 'DLO'), ('MG', 'MG'), ('GW', 'GW'), ('MO', 'MO'), ('OW', 'OW')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='team_position',
            field=models.CharField(blank=True, choices=[('OG', 'OG'), ('OO', 'OO'), ('CG', 'CG'), ('CO', 'CO')], max_length=2, null=True),
        ),
    ]
