# Generated by Django 3.2.5 on 2023-03-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakstracker', '0006_auto_20230311_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaks',
            name='include',
            field=models.BooleanField(default=True),
        ),
    ]
