# Generated by Django 3.2.5 on 2023-03-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakstracker', '0007_speaks_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaks',
            name='partner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='speaks',
            name='tournament',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
